language: bash
services: docker
install: false
env:
  global:
    - secure: "BZli0ieEVhvlhcOOjh+mYemo021rf5SpVSxrzOILrdZLZ0m5OGAOkwjgr7Mlmtl8fDT5KPZFmySR394OobuzEmYCkoGOUBpKJWFGV/vGVyizhZUBaFByohXfmQV2bvKLtJ/mWn77fBC2gpfueCqxflQ+qG6pIJ5yNIigiRM5kmiddNZf3Mtcp16haROQN0LIWqT7NKKdc+qx4IMFxZDBWBmzYm2DYgvwYiw58FJp8KZy2HkMPFbTg4D8KZumYiz70sY2Laj3EY8dPyiIHHKaoLJm8krlqXOrQxoSMSeKACnLzX96v676MvklXDulGdQbgvoGzdgx9zgSbXIh+8xG/wwdbe6v2Ze+B2LvlfBaM2qu9qAfr6wL3ULI1PaicbGqWZ7UhB2ItwLenPYEpTnb6ct6rfJxcnyPie4X3d8sx2tQ70RbMycoGWEpkeGDuyhm/FS/6dhhB3f0BAF1MwWU/HrY+YEBwubk6bL6D/wMInb+ZBmUBjyYggvNoEIG7QhnWuPDAc3KdCcMrUPW/O49ezh1onIycoB+ebhLVmlCM/5wpYpgSOd3q5EDZk3AGtr4YXxmfjz1jrUnd0HmodWsdbUYrCh3yv0SwJLf1/zznXWecCx25T1spdT5G72gHNBbXwZBkbcKVthX0LQng2a+kcNJbCMJ5U71pc62sOzsfXo="
    - secure: "bxeyp5Wlr5vwloHCbB3IGwf5vXFENbQ48qOiyKQPkq1ess6QhW+c2aVnhSHStnD+PPt+v4lxVG6wsqmu/gZQ24EAm38wXXQAc6u14akSpXh1MZR+FEuF/bWz26dGTam2E+4QqkYMpQIDZkOJxJe5YFGSK696goADiHje8OuOgB5NXf5asK5qAySnV4KzvD8lGei0jy0fwsEM7WNQnGRRvhRwUusIWYA+Z4+T8Y5/qgw60yocke0+iMQmGI7bgA35iudDNVGnBLAIJ55WyB1suQNJmmRlM63e3icArVFk9d++jmNr9dZh8/lsuWYnNq/Ze5fHopgQU3r98KMwydKqhMS7rIDH1mzECEhDBYX67ZsMO3RpPyQt9bg35KBsgThnwkVtzWLLPvBKNcUdxVQAi0c5zcw5d6v1SjdjvE2l9DzvplJzuRT7+LcTBe8Q+01oxJdOY8H+LJjd2bhhDArcKoo0iQEGnAN4z6b9ECQx+yvE4JijNpFKT8bRHnuzNnxh7uP/JF7HhILBbTO/aBK1x1FAJvc4l8VsKRXXs2fTmHfRR2IQ79Q0CaehTeH3qaYuDs84zCyIEVrHdtHsncBdiWt739iJLHHylEOWzTyITV73FfA4pJO+Lw3Lg/5JfWfNFcS4D0jofTGQ3ct7Yz6SoOr5FDJp7Wfx2w0OBWf+zGQ=" 

script:
- docker build -t rjshrjndrn/ansible:2.4.1 .
- docker run -d -p 8000:8000 rjshrjndrn/ansible:2.4.1
- docker ps
- bash -x test.sh
after_script:
- docker images
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
