language: bash
services: docker
install: false
before_script:
  - env | sort
  - image='hello-world'
script:
  - docker build -t rjshrjndrn/ansible:2.4.1 .
  - docker run -d -p 8000:8000 rjshrjndrn/ansible:2.4.1
  - docker ps
  - "./test.sh"
after_script:
  - docker images
env:
  global:
  - secure: e/2obBaf9LZ4KPIk4XR/bvVuT2m5TpIyo9Hy7hyH1vKUYEK7aaCLsew2M/ZvIXaNN9ehswd/wwTLT16+24ZWiY7YXGCTEi0UbrBNSEp7oNUWnE9s/vetXoFChfpXtmJyGSkaNhJJLHP+3q4bgGXGOv0Wctn3UIpghQx3zkBUNwd3UURNQB3xSQX/af+xvQfp/ILHPxEgiwAvHmRR26AdNSANxbcziDnZg9EO2J8iTn2x14ckiryMrP8JAXI6OGKtiS34W3prEam70ztv6JUDDz5qHmbvaKooHSdNufXcA7/FfoWp+z3g8+9QKtSN2ElHt8BHonre9gHYVpEkESp2MBPQP2xAlgbKLlZOIB+TF7O34TIMTh47miwqKwwr5H3SVu8/Ecn+Yrrk42xrXf5C9buEL7mdqmh0tyw+uSRhl4419uL8WvF7PCrTSIao+PQUunSf7S/dR3OCeHc1TvQmZ1wEQWjdY97CD7skXgS0i1hMVZwBluln1w3ZmqMe7sTvI/hjCA4cjU9MxM/tQVKL0/2LB8bQfnrwIHqW00Z/ccOtpAsr30ZV2FYH4HqYFbOEpnTghV6KtcvJlMMC8dEywlaYKhsE8ZKgkOJo00IVRBxJbSXYjsCSsVPiCcE5ibo7Vngdkg9/g7ujwIoDnnc7/rLxdHtCY4jC+3APNzjSmAA=
  - secure: G7xKn3igf5MzFOUn19Ns62uFpncvpd81WfCC6/CcaAE0WydAS5zKDOoUItMSoNwDSSmpj60e67ESWQucFU0Ukqe9wBQL2nGqAhYhzGdZ1aez6EK6NTJKLo8EO5yUFISakR9vlKMUfJURxW13tybbzLI3G2wJCfCllVPMVUmnudm48bK9K5fZ22uCXWZyNY5geG3qpU10p4Hh1ryPUW356Qm+gtOj35OwM8Ruo0sM8/c+DT7UCP7mlqaNVFtfIGblmVfA5CPnXYhpOQjNMqRj2sFNwnRzZo7SueACVh4774lU98O3gc6NBw1xZjRLgQkpYVH3fymzf69bI5hoFb48x6HpZSfwCFwwq/sKxuftlU9sQMPA6JUEjJjacsDQYZ6rAl50X9kQc6FBhhFPlnMowAEnua3TYsgTMn0btrj/UvXwQfim4gLd0XmAw8SXqILo/LfM+K3UYwd5xmgAHUsirCiBHPenqW6YZrbaMQYTyo06w769kpArStG1jtprWLsWSGRlbtRC7ocOuO2psFmd5/bWPe1Loayz+h0dAc6y62CPK23YuFfBPKj0eiBeUdl2xIlfYIs5FZj8nF6fBzzJQ9Ubj70tISZIogu1POAUrYyy+pFbXZ9QSovRpE5KhJWB37nRfM1d2x4h5dwCQSDdUYdP+JiB/cb0zytxSjGpcM0=

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
