language: bash
services: docker
install: false
env:
  global:
  - test=tester
  - secure: "SqwW9Q7TjBkI2+ei2Kk2uxGRNIlrvp1KcNssej8BONfSmS/FtFOWeh80HNdV4OYrPRQd8E7tMoXByg3njmU4nI4BeGV3f9ql3k33Mcm5zgR2+mFtNWjLofPvzl89T7XS+BpMECEmQDJL9exG56DZg2uThA4hJ2CFLV28hJb+PYgIJNQDE87njqUzoDf9d98fk8NctT/gbl1tAjpkQGxlAUYlkjOHwZjVutwZcsm551k355pprypzrXZlKyK3Lmxhwgka91kQg9EJFm5WZaNeJoDM2NlP4ueur2bopld9P9HLJgWMQH2i6DO8LJJLzfBwukzCHYTgzNZCKjL+YyKnToqQDPWFaqF3zBgn98kxVYEvNG9Co0JfS3rDcFhtD3nAKel3uXKQAHyAmClgIiWwF8DD+1a7poWTTlJumfM5/7ls60rbT3hxa7gSiRE5KZw0tV0bSbE0Wtd9+gEVLGsDWKwbaNfJKpDTyG0LKB6YyYp1TvGSxkSqAqOgDpPQ4LyC9/0ShYdQvglK+eMfCynGeCYqqhP5e3W96cSBRScV5CWu6Ku+8QuSfwoCSC6baQokoGPv8g1lSO29bpF3QBBnLG//2mOSpvPTXj7sEnmmGi6IL7i3bFWkziAMem4DhpftJm+6PBRLIAlcH+GhM6xIAi13qRpG691kE1dfpeSCyaQ="
  - secure: "eT4F89E6DggRy1nKPAiXU2kfTqAX1F4/itiDS9YyXZ7vebcRNWoxarDFFZ54ZA3jnjC4cabs7G9L7ZHkwTOqZlN10jEpoOfJK8IPgqoTlVCd/aHLto4Q+WhLdnNsy3o9WK2qHXE+dDro+sm8Z1xjiCYLlolWo2j8xxdpOPjV/1n0pUA6q4gA+J0AgBzrdwSovg/fiFdQVglKwzF+wnab6y/BDVU4HzrDl4S5GU/Mg0rC2YZfvxdh6hTCP2Kl1VOqEZNBfLNCVNyDoVrw4nUmRBnkUU/1m1XGJrp48uxXN8ftmGTdZ4NRx+zWkqSNk8ET5r9fceCw9JQAhKsTin052f9XlW78l2AjXHcILKUrJEeGVGj714VaJFxv6XAFUebmj1CKTOC8Hay6kOFZdSg0aFABBr37FsWXZAXkJc90E5YvaubADLq9/b1UUGhO4tAg9k4dOzRDd3J2GjiYDMoT9n2Ql5KxiaSef+Hb5gJ22N3jheV9NMyGFtdWZAKVNbrHmmkS5SEm4AFzfr1ba9melWNuMpmgIAJG0WYLediZRWNx/iG3TH4fSJjHgtD9SmYKCpmOVAjwDt+rR4bWEz/o4f9RFQuBDMjptKPzPAQ6T1/VEbnf1HyyEr0aQI9JJFcMCf+rTxZB2AOdmC5NyMQ+EZOF/YRkY+AVNcYmWiwlZd8="
script:
- docker build -t rjshrjndrn/ansible:2.4.1 .
- docker run -d -p 8000:8000 rjshrjndrn/ansible:2.4.1
- docker ps
- bash -x test.sh
after_script:
- docker images
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
