
language: bash
services: docker

install: false

before_script:
  - env | sort
  - image='hello-world'

script:
  - docker build -t test:latest .
  - docker run -d test:latest -p 8000:8000
  - docker ps 
  - ./test.sh

after_script:
  - docker images
