language: bash
services: docker
install: false
env:
  global:
  - secure: Y9xSHS+UKMVgDuUTHiXW93+/aGPKLuXyAizg6IK5zvc4bwt68XKwYINYvnkC0ok/llANt4KhOGAhQxi2uAfSgXZWunhaM1AJSx5msvvaKG2p1vAeHP3Sg+e0JzzgD9ax26TUqJXpHDjtKHAoTHDVTDSTW5A1i3xzbLWy2+UCXjs9FoGW3ozA1e5/AJecKzXEIyAhXxWEArgbfx31ea630inleNQqUaCqOYFnQef5N+zoQtPMJNPHa3+YZ2Utz2sKq/K7Nr7m9Qxj9RGn0Z7jDwwbXU5ESSZ8/VUPkBK6U+yLDtHW/IXLgGWy7DFSboaezMJv0M4CMWEVzAdSGOfJXmXfQTGrg2KOB5LM82MM5kYgDzmZmK8jNgYgBR6Uvdj+rtmS5Hcnm1gvq0ByInf3JPSZHo12vEYBh50YnQCXhlTD9RbOpisn26leAa7OuXoEfncsF1lKOjOTUUgfCL7D1sQi3LGPG0rThPLGqU90laRkpFr2okAFopNuHg96zPC5iMiocE2l/ow0qY9JFLNDoDxvITtoL8L31Q5LX60tx8FLc+izsfWZ0VT7WctEBvTUkrvgutYaB/uttBpuxdgF0CCKTpjhzW4wDwKHwn+TbZk6Jtq8LEl49xCdaEuVtfKSxG8nPI+y5r0m4j3fCl/Y4ZOVQPe7OF+7zzLQxtjG2Uk=
  - secure: BZbWD1NIZ/tX2q1d93hZqLJ6i821kj5czKKcXHxk6L74gXFvYksDblV9rneh/vG3Je+FMJRBN5DV99vsDbqVsjd0LmGlbXGcTnSjCOxKuCKMeg3yT6tuBbgRotkc6YB8DCdmTUSHANBmaoef9HbGFHCLcSmDaClP46dXPjXOX0XZWIfCwAlwmpffODbNLU9E8+VG9r7GxajqfswZMuaEEAJ8Ua1Sg8iY2o0+7atnwp80IwvJWuOAWRd0wtq94JFiR/txm+wEzAiYZ9nc3NJVdYlWTR91UV8jYoCKGCiP9Gue8qY2TaX6cnLydc+2Maysrv8n6AHS5xrdEllLqp0Nuri4XtKZ6lbSqkV0MxMEBjICnbmkQMUhHIMRcJclRMBrc9RE57wIozn4SEYXUoMuPdJRtn+hpEFIhwFHK3rAU973zaAv2EboLXYJNG0+drhEBFm0aYNP4VU1k3G8gsintn5aSB5/w1RXsEtP+ZeqyPAunf+ARf5E7MpnVHYvVHjGy7h1UPgEzD0mTtm2tJYH3/LPLClzj9UjngDeIW74yMzuOzslFlkzNtQ+N/lWIgzyJgOtJvLgNmXDWbGk5KTzhJeRXKwd3ZNi43CtV4uK7W/EGZj0DaRMnkVKtZXrr3prjp9r+9p9tR0w28fABfdPSKzA67HljXHfhvTfThMlFbg=
script:
- docker build -t rjshrjndrn/ansible:2.4.1 .
- docker run -d -p 8000:8000 rjshrjndrn/ansible:2.4.1
- docker ps
- "./test.sh"
after_script:
- docker images
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
