language: bash
services: docker
install: false
env:
  global:
    - secure: Ncnvc69X9gFETmUE+yQC4Mhp5pDQZbUYz3gqyCus15CO68yj1uJPFyqt1TVcFelgR/sivcJJ77LG0v+002gBo5M1Ck0K0GMVFYKwwnI/SswulKtLZRL7rpYNBWtDorQEv9x3tUabsk3+Pz9qYWJKx/2w5ZyAMzFzRthUkryzP2C/L8wK7Dq06YzgvCeqcvdMjhSyimAxm0JKXM2oxqSaHDEXw+kRmoOFTKe9eMmXyDRUZoVCswOJnHclHqWAPay7MCWuAhRRnKd1cGSpayyi/QR/wQRDumB3zxoiwWRyryNsGowiacGmpqhfufG0s6BkVhlmejDsuTaZpIDnG7uJDhlOLS0WEDbNzSdo9ZdhzLjM6eSNwoj7Gujxe8eIlc2G7R5kIJnGvM4CXfkFJUffn/tNerdIn7baK16vZpOwaZOdV7Bslogl+dT+mmVLgQ1kMdBti7rB+EFKkqggOKoRKcYickbWY9M6RBh0Bi68hI00Rev//lz8bthRUUtJm7IEWbpIhdjPIwUjzUo+Rj2w5G2GVCudI5sn5j5PcuS2x+GY/X4PAxCji3OMN6c9SHY4CGGEZtAQyTNzg5AJZU2VLfXndu+ymlpPuqU1//jRcuSR1E3I7o99L8NrxS35YSv0KJiAWNaUWO/Bd2WvxBaRTswIJbIcx/bEsRkiAQSwCPk=
    - secure: sxJnGovVjUtf51ScCNqevOd1L5fQ7fW5X+iVHqPVyyFI/zBsVmA3ONMbBUXeUGtGSAs/d8UvTH0/i7ZQf66b5CL09l7E50NXUMegEk88TSx6SP35sZ5ttgzAQtqf0IIneFPEtDgKMwYr9PbdzaF3ckYD3SZysXr2MUtJK6rS8ngGN99gkp/f8MOTF/cu2/YsGv/uMWVGgTzGonDtxw+fI4sspnxt6DdoPj+YAWILBnpv+99MeEr6Mkfw1uE9INRQvvXn0HJXL06ofB7zQrFth9Y/7Emwb0xUUht4nWn0zDUa3d7tn0OyyVF8h/27tqZwGSM/R0Y8IRmb6DUJnSZ5AUH8DXQbfw5jjMbaR0O2s7RDfioedqNuwmaQF6kfQZ4D+9OKi5fuGkD7r9nWyRvK45x/jvp2+AVGCJ5GSuIQLrTXEoieLui6zCW/dQHPOkObinic1gAbXcC6BwhrRfzOmn1EbsL3QibMn7fAL/gRAW1+NIiqXGS5QDCFjEjYaiVAmGlr7TrXqV74xGjqsGUqBmhiB85oXT0PqdDmWlzfJ+ogiA4bjQSR+3XbyTLzoxN1dmlYN+XOWxVV3MyEvAJD7FPx3kDvyvJwJy7vyXgu4pJxm7KHZa8QSGFghgN8wWkAev6xryKuMBQaCJ67KebCVHBQXMn2gsRgDBvg2STUxzQ=
script:
  - docker build -t rjshrjndrn/ansible:2.4.1 .
  - docker run -d -p 8000:8000 rjshrjndrn/ansible:2.4.1
  - docker ps
  - bash -x test.sh
after_script:
  - docker images
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
